server:
  port: 8082

spring:
  application:
    name: issues-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_jei
    username: root
    password: mysql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
